### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by timscrawls** [neatnik/omg.lol#169]
I keep asking for stuff..lol Sorry.

But either an glass.photo icon for profiles or maybe a generic profile item of photos? 

Thanks

**Comment by newbold** [comment]
Don't apologize for asking for stuff, @heyTimApple! The suggestions help make things better for everyone, so they're great!

I really need a better system for tagging/classifying profile items so that they can show an appropriate icon. The "schema-based" system that I'm using now is kind of awkward (e.g. `newsletter://`), and when I eventually roll over to a Markdown-based approach for profiles it's just going to look _weird_. And of course the whole point of Markdown is for things to look beautiful and natural! So I'm going to work on rectifying that very soon, and it’ll be so much easier to classify profile items once all is said and done (e.g. as photo things, or newsletter things, or blog things, etc).

In the interim, quick question for you — are you looking to add a link to your profile for `glass.photo` specifically? I can’t find a good icon for them, but I can easily wire up a nice generic photo icon to that URL specifically if that’s what you’re looking to do. Just let me know!

**Comment by timscrawls** [comment]
glass.photo is what I am going for but a generic icon should be fine and can cover other things in the future. I can use markdown to label the ling glass.

**Comment by newbold** [comment]
OK, I've got a camera icon in place for the `glass.photo` domain now! Let me know if there are any other services that you use that you'd like to get the same treatment.
