### ISSUE TITLE
Spark AR Icon Request

### ISSUE THREAD

**Issue by edizbaha** [neatnik/omg.lol#179]
Hi, can you add Spark AR icon to omg.lol? (Spark AR application is Meta's filter publishing platform.) Thank you :)

URL addresses are as follows: https://www.facebook.com/sparkarhub/portfolios/ig/username/

You can find the Spark AR icon here:
https://simpleicons.org/icons/sparkar.svg

**Comment by newbold** [comment]
All set!

**Comment by edizbaha** [comment]
@newbold It's shows Facebook icon when I add my URL.

**Comment by newbold** [comment]
Oh, yikes, I see what happened. It works with Markdown-formatted links, so if you do `[edizbaha](https://facebook.com/sparkarhub/portfolios/ig/edizbaha)` it should be fine. The reason it doesn’t work with the plain URL is because of the conflict with the existing Facebook icon. I’ll need to figure out a way around that, but until then, the Markdown workaround should take care of it for you!

**Comment by edizbaha** [comment]
@newbold thanks, right now Markdown is fine!
