### ISSUE TITLE
Allow Vanta.js as a background option

### ISSUE THREAD

**Issue by identithree** [neatnik/omg.lol#215]
**Is your feature request related to a problem? Please describe.**
I am currently experiencing issues with trying to get [Vanta.js](https://vantajs.com) working with my profile and it is getting a little infuriating.

**Describe the solution you'd like**
You should add a dropdown with all the Vanta backgrounds (along with a "none" option) and import the correct JS for that option. It would also be nice to be able to control the object values that gets passed to Vanta so we can customize color and interactivity.

**Describe alternatives you've considered**
I tried accomplishing it by injecting scripts into the head. That didn't work as they loaded too early and I couldn't properly set an HTML id to the body tag along with loading Vanta in time.

**Additional context**
It would allow for additional customization like this.
![image](https://user-images.githubusercontent.com/71232944/193043424-56ba2842-6d1a-4a1a-8651-d924f399172d.png)

**Comment by newbold** [comment]
Wow, I’d never heard of Vanta.js before (autocorrect just changed it to Santa, which seems appropriate because it feels like Christmas!). Very cool. I just tried it out and I was able to get it working by wrapping its main script in a an event listener that fires when the DOM has fully loaded. Also noticed that I needed to make a couple of style changes (the most important one being to set an explicit height value on the html element, or else the background wouldn’t fully cover the page). The other style change was to boost the opacity of the main element so there’d be better contrast against the background. Finally, I noticed that Vanta lets you target elements, not just selectors, so I was able to say "yo, do this on the 'html' element" and it totally worked!

So, on omg.lol, here’s what I have on my test page:

CSS:

```
html {
	width: 100vw;
	height: 100vh;
}
main {
	background: rgba(255, 255, 255, .8);
}
```

<head> thing:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.birds.min.js"></script>
<script>
window.addEventListener('load', (event) => {
	VANTA.BIRDS({
		el: "html",
		mouseControls: true,
		touchControls: true,
		gyroControls: false,
		minHeight: 200.00,
		minWidth: 200.00,
		scale: 1.00,
		scaleMobile: 1.00
	})
});
</script>
```

And you can see it live here: https://a.omg.lol

Let me know if you run into any issues with any of this! It’s possible that certain themes might be a little wonky (I did everything above with the Default theme.) Glad to help if you run into problems though.

**Comment by identithree** [comment]
> Wow, I’d never heard of Vanta.js before (autocorrect just changed it to Santa, which seems appropriate because it feels like Christmas!). Very cool. I just tried it out and I was able to get it working by wrapping its main script in a an event listener that fires when the DOM has fully loaded. Also noticed that I needed to make a couple of style changes (the most important one being to set an explicit height value on the html element, or else the background wouldn’t fully cover the page). The other style change was to boost the opacity of the main element so there’d be better contrast against the background. Finally, I noticed that Vanta lets you target elements, not just selectors, so I was able to say "yo, do this on the 'html' element" and it totally worked!
> 
> So, on omg.lol, here’s what I have on my test page:
> 
> CSS:
> 
> ```
> html {
> 	width: 100vw;
> 	height: 100vh;
> }
> main {
> 	background: rgba(255, 255, 255, .8);
> }
> ```
> 
> thing:
> 
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.birds.min.js"></script>
> <script>
> window.addEventListener('load', (event) => {
> 	VANTA.BIRDS({
> 		el: "html",
> 		mouseControls: true,
> 		touchControls: true,
> 		gyroControls: false,
> 		minHeight: 200.00,
> 		minWidth: 200.00,
> 		scale: 1.00,
> 		scaleMobile: 1.00
> 	})
> });
> </script>
> ```
> 
> And you can see it live here: https://a.omg.lol
> 
> Let me know if you run into any issues with any of this! It’s possible that certain themes might be a little wonky (I did everything above with the Default theme.) Glad to help if you run into problems though.

Thank you so much! It works beautifully. https://quinnlane.dev/
