### ISSUE TITLE
[Icon] for MLTSHP

### ISSUE THREAD

**Issue by dieseltravis** [neatnik/omg.lol#376]
### What service is this for?

MLTSHP (malt shop) is an open-sourced, community run and funded image sharing website. More info here: https://mltshp.com/faq/

### What are their domain names?

https://mltshp.com/

### Do you have a link to a SVG of their logo?

https://github.com/MLTSHP/Logo-and-Design-Assets/blob/master/profile-icons-rounded/profile-rounded-icon-small.svg

**Comment by dieseltravis** [comment]
I tried using the `{cup-straw}` icon since it was the closest thing to the MLTSHP logo, but that didn't seem to work right either:
![image](https://user-images.githubusercontent.com/17863/201508845-a03a3b20-fc18-463d-aa8a-c6489f8bc981.png)
![image](https://user-images.githubusercontent.com/17863/201508859-37ecf655-dd8d-4daf-a102-f2898da2669f.png)

**Comment by lxjv** [comment]
hey @dieseltravis, the `{cup-straw}` icon cant be used as its part of Font Awesome Pro, which we aren't allowed to use in the selectable icon-set :(

**Comment by newbold** [comment]
Icon added! Because of caching it may take a few refreshes before it shows up, but I’m now seeing it on this end. Thanks for the suggestion!

<img width="146" alt="Screenshot 2022-11-13 at 11 17 05 AM" src="https://user-images.githubusercontent.com/986721/201532201-9b6e453a-711e-42f7-bbf7-a1501f734073.png">
