### ISSUE TITLE
Long Profiles Items are not easily editable on small screens

### ISSUE THREAD

**Issue by swizzlevixen** [neatnik/omg.lol#394]
### Bug Description

If I access omg.lol web site settings on my iPhone and I have a profile item with content that is long enough to word wrap, the height of the field does not expand to show the full content.

At first it did not seem possible to scroll in the field to edit content below the first line, because it would not scroll if you use the iPhone technique of using a touch and drag on the space bar to move the cursor. It seems that you can scroll if you touch and drag inside the field, but it’s still quite clunky.

![257807E0-CAE3-4C05-B595-F2AF08EED036](https://user-images.githubusercontent.com/50014/203585500-30bff405-a5d4-4b01-9524-321ec8291785.png)
 
_Aside: Thanks for the great service! Loving it so far <3_

### Steps to Reproduce

1. Create a long Profile item with a browser on a device with a larger screen, for example: `[Station in the Metro](https://www.stationinthemetro.com) {house} <small>(this may be broken)</small>`
2. View the Profile Items section of the web page settings on an iPhone held in portrait mode
3. Tap into the field to edit the profile item
4. Touch and drag on the space bar to attempt to move the cursor down to the second line, after word wrap
5. The cursor will stay on the first line
6. Touch and drag downward in the field itself
7. The content of the item will scroll, and you can edit it, but it’s still a clunky experience because it’s very difficult to control the speed of the scroll or the exact location of the cursor this way

**Comment by newbold** [comment]
Thanks for reporting this. I feel bad, because this is one of those things that’s probably plagued folks since forever, but was off of my radar because no one took the time to report it until now. And I really appreciate the detailed bug report!

After some poking around, I was able to apply what I think is a pretty effective solution. Now, when your profile page loads, your profile items will be sized to fit the contents of their `<textarea>`s, and those same elements will grow as input is received. Overall, this should be a _much_ smoother experience. Let me know if you notice any issues with it or have any other feedback. Thanks!

**Comment by swizzlevixen** [comment]
This revised version looks great, thank you so much for the quick response!
