### ISSUE TITLE
[Bug] CAA record syntax

### ISSUE THREAD

**Issue by fm** [neatnik/omg.lol#397]
### Bug Description

Can't create new CAA records. One thing I forgot to mention last night is that the CA entity must be sent in quotes and the stuff _**inside**_ the quotes is the one that must have no spaces.

<img width="1242" alt="Screenshot 2022-11-26 at 11 32 21 AM" src="https://user-images.githubusercontent.com/3654256/204084295-35ad86a1-b889-478e-a8e3-406fa7a2d9a0.png">

I also suggest setting the placeholder name to `@` instead of `foobar`.

**Comment by newbold** [comment]
Thanks for catching this. Clearly my late-night (well, early morning) quality controls were... not good. The problem here was that the code I was using for the migration was assembling the CAA records from separate components, and it worked for the _migration_, but wasn’t fit to be used for new record creation. I’ve just cleaned that up, though, and set the field placeholder to display the expected data format.

<img width="485" alt="Screenshot 2022-11-26 at 11 45 22 AM" src="https://user-images.githubusercontent.com/986721/204099568-47e11cd6-06b2-4d53-8a02-3d90d4e4782c.png">
