### ISSUE TITLE
[Bug]  When deleting a weblog post, all posts get deleted

### ISSUE THREAD

**Issue by voclain** [neatnik/omg.lol#405]
### Bug Description

I made several test posts, and when I deleted one they all disappeared. I didn't mind because I didn't intend in keeping them, but it surprised me.

I know this feature is brand new and this might already be a known bug, but I thought I ought to note it here anyway.

Thanks for all the wonderful work you're doing! 

### Steps to Reproduce

Deleting a post

**Comment by newbold** [comment]
Thanks for letting me know — it turns out that only the specific posts were deleted, but everything else appeared to be deleted because of a metadata cache mishap. The good news is that it’s easy to regenerate the post metadata cache, so I’ve just done that for everyone. You should see all of your posts once more.

Apologies for the overall bugginess during this pre-pre-alpha, most-certainly-not-ready-for-use phase of the service. 😄
