### ISSUE TITLE
[Bug] weblog.lol: post title should be h2 not h1

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#416]
### Bug Description

Per w3c validator:

> Consider using the h1 element as a top-level heading only (all h1 elements [are treated as top-level headings by many screen readers and other tools](https://html5accessibility.com/stuff/2021/07/08/preserved-in-html/)).

So, h1 should be reserved for the weblog title.

(I only found this because I'd screwed up something else in my template that also wasn't validating.)

**Comment by newbold** [comment]
[The accepted answer on this Stack Overflow article](https://stackoverflow.com/questions/25996074/w3c-validation-says-h1-in-article-is-invalid) does a great job of explaining what’s going on here.

It’s totally valid to use an `<h1>` inside of a semantically-appropriate block-level element, like `<article>`. At the same time, it can cause trouble for folks who are using outdated screen readers or screen readers that haven’t been brought up to the latest standards and that don’t recognize or respect HTML5’s semantic structures.

Ultimately, it’s up to you to decide if the warning merits action. The easiest action to take would be to simply change your `#` to `##` in your posts, which will generate an `<h2>` instead of an `<h1>`. You’re in total control!

**Comment by newbold** [comment]
Also, an odd detail — the W3C's "Nu Html" validator will throw the warning and not declare the page as valid, but the standalone version at https://html5.validator.nu will throw the same exact warning but _does_ declare the page as valid. Weird.
