### ISSUE TITLE
If I buy a subdomain for a year, what will happen to my Mastodon account on social.lol after the year passes?

### ISSUE THREAD

**Issue by RDKRACZ** [neatnik/omg.lol#484]
Do I lose access to the Mastodon server if I don't extend my subdomain?

**Comment by fm** [comment]
Great question! We need to do a write-up on this. It hasn’t happened yet, but the process that we intend to follow is one in which the account holder has an opportunity to fully migrate to another instance and/or export any data before their account is removed. Ultimately, expired accounts will be removed (and where Mastodon is concerned, they’d be removed in a way that fully de-federates the account, removing all followers, etc). Hope this makes sense!

**Comment by lxjv** [comment]
will write this up now, @fm !

**Comment by RDKRACZ** [comment]
Any plans for allowing users to buy access to social.lol for a lower price, without that subdomain?

**Comment by stan754** [comment]
I don't think so because the username is always the same as the subdomain so you'd hold someone elses name

**Comment by lxjv** [comment]
answering this for @newbold as i think i know the answer:

no

**Comment by RobertoVillegas** [comment]
> Any plans for allowing users to buy access to social.lol for a lower price, without that subdomain?

@RDKRACZ That has been mentioned on the IRC server and as far as I'm concerned there's no plan to sell the omg.lol serviced separately. That would break the purpose of omg.lol because as @newbold writes, ["Addresses are what omg.lol is all about. Your address is your identity, your chunk of real estate in the omg.lol namespace."](https://home.omg.lol/info/addresses)
