### ISSUE TITLE
[Bug] Hybrid branding loaded over http in /web preview

### ISSUE THREAD

**Issue by plttn** [neatnik/omg.lol#495]
### Bug Description

the Hybrid branding PNG is loaded over HTTP: `img class="prami-logo" src="[http://static.omg.lol/img/prami_hybrid.svg](view-source:http://static.omg.lol/img/prami_hybrid.svg)"> Powered by omg.lol`

rather than HTTPS

**Comment by newbold** [comment]
@plttn I think I fixed this a while ago, though because profile pages exist as cached static content, any profile page that hasn't been republished since the fix would still have the flawed source. I can't remember exactly when I fixed it, so I think it was a while ago... Do you happen to know what address you saw this on so I can take a look?

**Comment by plttn** [comment]
Mine.

**Comment by newbold** [comment]
Found it in the editor! Thanks!

**Comment by plttn** [comment]
Fixed
