### ISSUE TITLE
[Bug] Dashboard: Weblog pane includes pages in post count

### ISSUE THREAD

**Issue by bixfrankonis** [neatnik/omg.lol#535]
### Bug Description

While this counting bug was fixed for actual published weblogs, I just noticed it’s still there in the omg.lol Dashboard.

**Comment by newbold** [comment]
So, this is kind of intentional, but also a little confusing. I’m using the term “entries” there, which as far as weblog.lol is concerned mean posts + pages, but... I’m now realizing that the more typical use of the term entry is synonymous with post, and that pages are something else entirely.

Ultimately some folks might use weblog.lol with pages only (no posts), and that’s perfectly fine... but I don’t want them to see "no entries yet" or "no posts yet" or whatever. But now I feel like I'm doomed to generate confusion here no matter what, heh.

If you have any thoughts, I'm all ears!

**Comment by newbold** [comment]
Items sounds great! Just ran with it. Thanks!
