### ISSUE TITLE
[Bug] API gives random behavior (401/200)

### ISSUE THREAD

**Issue by wayneyaoo** [neatnik/omg.lol#635]
### Bug Description

Starting a few days ago, I notice my integration tests (tests that send to real api with token and assert stuff) begins to give random pass/fail ...  This is true on my manual browser reproduction. is it because of the added cache (cached: true)?

e.g., requesting https://api.omg.lol/address/adam/info would fail/pass randomly. I mean with some pattern, like after my IDE test runs failed, I open browser and try, and it gives 401, then I ctrl-r to force refresh then it works again, then I come back to IDE the test works too... the "cached: true" definitely worth looking into.. is this expected?

**Comment by newbold** [comment]
I did recently add some caching to responses, and the `cached` value in the response is present when the response is being served from the cache. Eventually this will be expanded to be included with every response (with a true/valse value) and when true, it will include the TTL expiry value for the cached response (or at least that’s my goal).

I’m not yet sure if there’s any connection between the cached value and any 401 responses. When you get a 401, what’s the `message` that’s included in the response?

**Comment by newbold** [comment]
Thanks, that's helpful. I just made an adjustment — authenticated requests should no longer be cached. In theory, that should address the issue. Can you confirm? Thanks!

**Comment by vtheskeleton** [comment]
unrelated but would it not make sense for the cached boolean to be part of request

**Comment by vtheskeleton** [comment]
Sorry, let me clarify and also sorry for bringing up something completely unrelated in this issue
What i meant was wouldn't it make more sense if it was 
```json
{
	"request": {
        "status_code": 200,
        "success": true,
        "cached": true
    },
    ...
}
```

rather than 
```json
{
	...
	"cached": true
}
```

However what you mentioned made me wonder about that too, does the API caching respect the Cache-Control header?

**Comment by newbold** [comment]
@vtheskeleton Ah, I see what you mean. I just stuck it on there on its own as a quick way to say "you're seeing cached stuff" without a whole lot of thought. But thinking about it a tiny bit now, I kind of like the idea of the indicator being separate, as a way to indicate that 100% of what's in the `response` value is indeed cached (excluding the cached indicator itself, which would be confusing when you start to think about whether the thing that says something is cached or not is potentially subject to being cached itself...).

As for the Cache-Control header, I could be wrong but I thought that was primarily intended for the benefit of browsers (specifically so a remote resource can signal when/how the browser should cache stuff on its own). When you talk about "respecting" the header, can you share a little more info about what you mean? Are you suggesting that the omg.lol API should take directives from applications that emit the header, or that the API should emit the header itself so that browsers/applications can get more specific info about the caching being performed at the API level? (I do plan to add that info to the `cached` element at some point.)

**Comment by newbold** [comment]
Oh, I see now. Since this is a (new, experimental, and evolving) cache policy intended to support service health, I don't think I'd want to allow overrides. I haven't done any kind of write-up on it yet or anything, but I'll share that there's some thought into the initial setup — including that actions which modify a resource (like updating your profile page) will purge the cache for that resource, ensuring that no one receives stale output for a recently updated thing. It's really just intended to alleviate pressure on the database.

**Comment by wayneyaoo** [comment]
Coming back to the issue:

I had a repro!!!! I think I hit a edge case ... where a cached 401 response got sent to a concurrent, legitimate, public, but has-the-same-endpoint-signature request. I can even repro with mouse if I click quick enough loooooooooooool.

Try this out (this is sooo fun looool, if this turns out to be a real bug I'm gonna buy myself a pizza today...):

Using postman, in one tab, type url: https://api.omg.lol/address/adam/info. In another new tab, type the same url but also pass in an invalid api key (e.g., 123). So we have two same request, one without token, one with an invalid token. We expect two request to be independent, and return a 200 and 401 respectively.

But if you send the two requests close enough (click quickly), you see both requests getting 401. Try a few more times if it doesn't work.

**Comment by vtheskeleton** [comment]
This seems to also work the other way...
I made an authenticated request in postman for /address/amelia/info and then navigated to it in the browser and saw a cached response containing the authenticated response
![image](https://user-images.githubusercontent.com/47392011/224348369-11c09738-c7f1-4751-9c05-ffc6a21b4220.png)
![image](https://user-images.githubusercontent.com/47392011/224348435-85378058-40bd-42d6-89eb-70704a286a11.png)

**Comment by wayneyaoo** [comment]
omg I confirmed this. This is a vulnerability then!... I double confirm this on two separated devices (one mobile, one pc), that requesting with token in one device, and refreshing the same endpoint without token in another device will get authenticated information..

That means if I keep polling for everyone's public address there's a small chance that I get authenticated info...

: ) Can I please get a line the Hall of Fame?

**Comment by wayneyaoo** [comment]
I think I'll ... use email to communicate this rather than publishing this publicly (though I already did.. and there's no way to revert it).

**Comment by newbold** [comment]
> I think I'll ... use email to communicate this rather than publishing this publicly (though I already did.. and there's no way to revert it).

GitHub offers an edit feature. And omg.lol has a [responsible disclosure policy](https://home.omg.lol/info/bugs).

**Comment by vtheskeleton** [comment]
GitHub edit history is unfortunately public

**Comment by wayneyaoo** [comment]
I'm so sorry ... didn't realize until I hit send.. an email was sent to you with extra details.

**Comment by Vukkyy** [comment]
You can delete entries in the edit history, unless that's what you were referring to

**Comment by wayneyaoo** [comment]
Deleted everything. Sorry my bad. Let's continue this conversation in a separated place.

**Comment by newbold** [comment]
I've removed caching from API responses which I believe resolves all issues discussed here. I will add it once more when I have time to do so safely and properly. Thanks.
