### ISSUE TITLE
some icon requests! :)

### ISSUE THREAD

**Issue by lakerjv** [neatnik/omg.lol#72]
could you add:

- [x] Notion (https://notion.so / https://[example].notion.site)
- [x] Write.as (https://write.as)
- [x] Polywork (https://polywork.com / https://poly.work)
- [x] Lichess (https://lichess.com)

if not, no hard feelings :)

**Comment by newbold** [comment]
Great suggestions! Already had Polywork but not the poly.work domain — so I added that along with the others. Can you confirm that you meant lichess.org instead of lichess.com? I can't get the latter to load, but if you meant .org you're good to go! Here's how they look:

<img width="104" alt="Screen Shot 2021-09-28 at 4 56 31 PM" src="https://user-images.githubusercontent.com/986721/135164623-34c366fc-8eba-4e98-83a1-3f64ef262ea7.png">

**Comment by lakerjv** [comment]
I did! thank you :)

**Comment by lxjv** [comment]
MY FIRST ISSUE WAS A YEAR AGO?!?!?!
